# Change these first
owner: tjor75 # Your GitHub organization or username, where this repository lives
repo: eort # The name of this repository

sites:
  - name: ORT.edu.ar
    url: https://www.ort.edu.ar
  - name: Campus Virtual
    url: https://campus.ort.edu.ar
  - name: Z online
    url: $URL_ZOL
  - name: Bibliotecas
    url: $URL_BIBLIOTECAS

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /eort
  robotsText: "User-agent: * \n Disallow: /"
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: EstadoORT
  introTitle: "¿Es un problema mio?"
  introMessage: Esta página web contiene información actualizada sobre el servicio de las páginas de ORT y un historial de caidas para que puedas enterarte si el problema es tuyo o pasó algo más. Soy un estudiante y mi nombre se encuentra en el GitHub vinculado arriba, responderé cualquier duda o solicitudes para terminar esta página web. Vale decir que esta página web **no está afiliada de ninguna forma con la Asociacion ORT Argentina y/o afiliados**.
  navbar:
    - title: Ahora
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
